# SPDX-FileCopyrightText: 2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

name: TDLib Update
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  update-tdlib:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04

    # noinspection SpellCheckingInspection
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
      - name: Check out the sources
        uses: actions/checkout@v6

      - name: NuGet cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('Scripts/*.fsx') }}
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v5

      - id: update-tdlib
        name: Update TDLib
        shell: pwsh
        run: dotnet fsi ./Scripts/update-tdlib.fsx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && steps.update-tdlib.outputs.has-changes == 'true'
        name: Create a pull request
        uses: peter-evans/create-pull-request@v8
        with:
          author: TDLib automation <friedrich@fornever.me>
          body: ${{ steps.update-tdlib.outputs.body }}
          branch: ${{ steps.update-tdlib.outputs.branch-name }}
          commit-message: ${{ steps.update-tdlib.outputs.commit-message }}
          title: ${{ steps.update-tdlib.outputs.title }}
